// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }






// // app/layout.tsx
// import { ClerkProvider } from '@clerk/nextjs'
// import { ReactNode } from 'react'

// export default function RootLayout({ children }: {children: ReactNode}) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body>{children}</body>
//       </html>
//     </ClerkProvider>
//   )
// }





// // app/layout.tsx

// import { ClerkProvider } from '@clerk/nextjs'
// import { Inter } from 'next/font/google'
// import './globals.css'
// import { Toaster } from 'sonner'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Blood Donation App',
//   description: 'Connect blood donors with those in need',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body className={inter.className}>
//           {children}
//           <Toaster position="top-center" richColors />
//         </body>
//       </html>
//     </ClerkProvider>
//   )
// }





import { ClerkProvider } from '@clerk/nextjs'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
import { ThemeProvider } from '../components/theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blood Donation App',
  description: 'Connect blood donors with those in need',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider>
            {children}
          </ThemeProvider>

          <Toaster position="top-center" richColors />
        </body>
      </html>
    </ClerkProvider>
  )
}

